name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Deploy only when code is pushed to main branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js (adjust version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build (optional if Vercel does it automatically)
      - name: Build project
        run: npm run build

      # 5. Deploy to Vercel using CLI
      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --token=$VERCEL_TOKEN --prod --confirm --scope=$VERCEL_ORG_ID
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
